feat: styles
modelscope/modelscope-agent pull request #92
Opened 2023-11-18 09:27 UTC by justmywyw

- 增大 Preview 部分对话框高度
- 优化对话框内容 调用链样式

2023-11-19 03:08 UTC, wenmengzhou requested changes
请执行pip install pre-commit && pre-commit install  && pre-commit run --all-files

2023-11-20 01:52 UTC, justmywyw commented
> 请执行pip install pre-commit && pre-commit install && pre-commit run --all-files

lint fixed ～

2023-11-20 06:53 UTC, justmywyw commented
- 修复 merge 多余部分

2023-11-20 11:08 UTC, wenmengzhou approved these changes

2023-11-20 11:08 UTC, merged